### ISSUE TITLE
提示伺服器錯誤

### ISSUE THREAD

**Issue by veecam** [afq984/void-battery#2]
https://void-battery.appspot.com/pob/?accountName=lr5188888&character=%E5%B4%87%E9%AB%98%E6%88%91%E9%80%99%E5%AD%A3%E8%B6%85%E5%8B%87%E7%9A%84

**Comment by veecam** [comment]
稀有度: 傳奇
希望之絃
赤紅珠寶
--------
範圍: 可變的 (augmented)
--------
物品等級: 86
--------
對中範圍內天賦造成影響
天賦樹中在範圍內未連結的技能仍然可以配置
-10% 全部元素抗性
--------
雖然我們不能碰觸； 一個想法，一個願望，在黑暗中獨自走了幾個世紀。
--------
放置到一個天賦樹的珠寶插槽中以產生效果。右鍵點擊以移出插槽。





只要裝備上這顆珠寶就會提示錯誤

**Comment by Splendent** [comment]
這邊也碰到同樣問題==

**Comment by prototypeSean** [comment]
同問, 巴哈有人說軍團珠寶,但拔掉也是相同錯誤

**Comment by afq984** [comment]
@prototypeSean 

Hi, 最近超忙，大概三月底到四月初才能修
thx

如果巴哈有人有時間能幫忙看 code 的話也歡迎 XD
（github 上面的 code 跟網站上的是一樣的；chrome 的擴充套件有允許本地存取方便除錯）

**Comment by biboy1999** [comment]
https://www.reddit.com/r/pathofexile/comments/fijblb/is_this_happening_for_anyone_else_or_is_it_just_me/
提示伺服器錯誤應該是GGG意外移掉API的`jewel_slots`

**Comment by afq984** [comment]
See https://github.com/afq984/void-battery/issues/5 for stack trace.

**Comment by afq984** [comment]
「可變的」應該已經解決，如果還有其他問題再開其他 issue
