### ISSUE TITLE
about chrome_extension

### ISSUE THREAD

**Issue by dolphinlin** [afq984/void-battery#21]
想詢問做這 關於 `chrome_extension`
這個功能看起來單純只有 fetch`character info`
請問怎麼會需要特別做一個 `extension` 來拿資料呢？

**Comment by afq984** [comment]
因為 poe 的 api 沒開 [CORS]，直接從 javascript 送 request 會被瀏覽器攔下來

你可以試試看在網站上面開 console 打 `fetch('https://web.poe.garena.tw/character-window/get-items?accountName=XXX&character=YYY')` (把 XXX 跟 YYY 換掉)

[CORS]: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by dolphinlin** [comment]
好的 我不知道有 cors 因為就單純看 code 好奇而已 感謝！
感謝！
