### ISSUE TITLE
錯誤：無法翻譯此詞綴：附加的小型天賦給予 #

### ISSUE THREAD

**Issue by biboy1999** [afq984/void-battery#3]
Kyusung4698/PoE-Overlay#324
GGG 把詞綴混在一起==
導致程式認不出詞綴

附加的小型天賦給予：# 
+
增加 #% 暴擊率
= 附加的小型天賦給予：增加 #% 暴擊率

在遊戲內珠寶會顯示
```
稀有度: 稀有
鷹翼撫慰
中型星團珠寶
--------
物品等級: 69
--------
附加 5 個天賦 (enchant)
附加的小型天賦給予：增加 15% 暴擊率 (enchant)
--------
1 個附加天賦為苦痛之基
1 個附加的天賦為壓力點
1 個附加的天賦為珠寶插槽
--------
放置於天賦樹已配置的中型或巨型珠寶插槽中。附加的天賦點不與珠寶範圍互動。點擊右鍵從插槽中移除。
```

**Comment by afq984** [comment]
感謝你幫忙找出問題，你要發個 pull request 過來嗎？

**Comment by afq984** [comment]
fixed by #4

**Comment by afq984** [comment]
似乎還是有些詞綴沒有辦法被翻譯，`stats_descriptions.json` 裡面的東西可能不夠多
舉例來說：
```
nebuloch.mods.CannotTranslateMod: '附加的小型天賦給予：增加 10% 元素傷害'
```
要找一下這些詞綴在遊戲數據的哪裡了。
https://poedb.tw/tw/item.php?n=Large+Cluster+Jewel

**Comment by biboy1999** [comment]
```
 def match(self, mod_string):
        match = re.match(self.matcher, mod_string)
        if match is None:
            return match
        values = self.default_values[:]
...
mod_string = '附加的小型天賦給予：增加 12% 烙印技能傷害'
self.matcher = '\\增\\加\\ (\\-?\\d+(?:\\.\\d+)?)\\%\\ \\烙\\印\\技\\能\\傷\\害'
```

mod是不是也要一起切掉，後面的match regex才對得到詞?

**Comment by afq984** [comment]
你是對的QQ

**Comment by Arisix** [comment]
> 似乎還是有些詞綴沒有辦法被翻譯，`stats_descriptions.json` 裡面的東西可能不夠多
> 舉例來說：
> 
> ```
> nebuloch.mods.CannotTranslateMod: '附加的小型天賦給予：增加 10% 元素傷害'
> ```
> 
> 要找一下這些詞綴在遊戲數據的哪裡了。

Trade API裡面有詞綴表
可能可以從這邊獲得完整的詞綴

http://web.poe.garena.tw/api/trade/data/stats

**Comment by afq984** [comment]
> Trade API裡面有詞綴表
> 可能可以從這邊獲得完整的詞綴
> 
> http://web.poe.garena.tw/api/trade/data/stats

看起來可行，跟國際服的 ID 是一樣的

**Comment by RealWei** [comment]
才剛想說沒這個真的好不方便，來看看能不能幫個忙，結果已經改完了XD

感謝你們的付出

**Comment by afq984** [comment]
看了下後台
似乎這個問題確實已經解決了 再次感謝 @biboy1999 的協助

@RealWei 我把其他後台抓到的錯誤也開成 issue 了，如果你有興趣的話也可以研究
抓 trade API 的詞綴做一半... 有點懶的弄了 先丟[這邊](https://github.com/afq984/void-battery/tree/tradeapistats)
